name: sport_application
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  contained_tab_bar_view: ^0.8.0
  step_progress_indicator: ^1.0.2
  font_awesome_flutter: ^10.3.0
  smooth_page_indicator: ^1.0.0+2
  percent_indicator: ^4.2.2
  liquid_progress_indicator: ^0.4.0
  multi_dropdown: ^1.0.6
  video_player: ^2.4.10 #
  appinio_video_player: ^1.2.0
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.2
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.0.15
  get: ^4.6.5
  awesome_snackbar_content: ^0.1.0
  persian_datetime_picker: ^2.5.0
  dots_indicator: ^2.1.0
  carousel_slider: ^4.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
   
  
    

flutter:
  uses-material-design: true
  assets:
   - images/
  fonts:
  - family: iranyekan
    fonts:
      - asset: fonts/iranyekan.ttf
        weight: 400
      - asset: fonts/iranyekan-extrablack.ttf
        weight: 500
      - asset: fonts/iranyekan-bold.ttf
        weight: 700
      - asset: fonts/iranyekan-black.ttf
        weight: 300
