name: sport_application
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  contained_tab_bar_view: ^0.8.0
  step_progress_indicator: ^1.0.2
  font_awesome_flutter: ^10.3.0
  smooth_page_indicator: ^1.0.0+2
  percent_indicator: ^4.2.2
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.2
  internet_connection_checker: ^1.0.0+1
  get: ^4.6.5
  awesome_snackbar_content: ^0.1.0
  persian_datetime_picker: ^2.5.0
  dots_indicator: ^2.1.0
  get_storage: ^2.0.3
  carousel_slider: ^4.2.1
  http: ^0.13.5
  flutter_ruler_picker: ^1.0.3
  sizer: ^2.0.15
  flutter_chat_ui: ^1.6.6
dev_dependencies:
  flutter_test:
    sdk: flutter
   
  
    
flutter:

  uses-material-design: true
  assets:
   - images/
  fonts:
  - family: iranyekan
    fonts:
      - asset: fonts/iranyekan.ttf
        weight: 400
      - asset: fonts/iranyekan-extrablack.ttf
        weight: 500
      - asset: fonts/iranyekan-bold.ttf
        weight: 700
      - asset: fonts/iranyekan-black.ttf
        weight: 300
